// src/reducer/actionTypes.js
const actionTypes = {
  NEW_MOVE: 'NEW_MOVE',
  SET_CANDIDATE_MOVES: 'SET_CANDIDATE_MOVES',
  COMPLETE_PROMOTION: 'COMPLETE_PROMOTION',
  SET_PROMOTION: 'SET_PROMOTION',
  CASTLING_MOVE: 'CASTLING_MOVE',
  SET_CHECK_STATUS: 'SET_CHECK_STATUS',
  CHECKMATE: 'CHECKMATE',
  STALEMATE: 'STALEMATE',
  RESET_FOR_REPLAY: 'RESET_FOR_REPLAY'

  // Add more types if needed
}

export default actionTypes
